name: Mirror to Gitee

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  mirror-to-gitee:
    uses: yilunyuwan/test-rui/.github/workflows/template-mirror.yml@master
    secrets: inherit