name: Mirror GitHub to Gitee

on:
  workflow_call:

jobs:
  mirror-to-Gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: Yikun/hub-mirror-action@master
        with:
          src: github/yilunyuwan
          dst: gitee/yilunyuwan
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "test-rui"